### ISSUE TITLE
Building fails with (new?) nimble. Tests also fail but for another reason.

### ISSUE THREAD

**Issue by oderwat** [zielmicha/reactor.nim#1] opened 2016-01-09 23:04 UTC
Hi... I tried to build with Nimble (0.7.0) from 2.1.2016 and got this:

```
nimble build
Traceback (most recent call last)
nimble.nim(960)          nimble
nimble.nim(885)          doAction
nimble.nim(867)          execHook
packageparser.nim(232)   readPackageInfo
packageparser.nim(74)    validatePackageInfo
packageparser.nim(28)    raiseNewValidationError
packageparser.nim(28)    raiseNewValidationError
... continues
```

Now I rebuild Nimble and this time Nimble build "hangs".

I also saw this:

```
./runtests.py
Traceback from system (most recent call last)
Error: unhandled exception: cannot open: /Users/hara/devsys/workspace/nim/reactor.nim/reactor/uv/../../deps/libuv/src/fs-poll.c [IOError]
```

Which may not be your intention. I can install libuv on mac by homebrew and would not have any code then?

Maybe I do something wrong anyway. Maybe some build instructions would help with that!

P.S.: `nimble install reactor` also hangs for me
P.P.S.: The original reason I was going to check you repo out was that I wanted to see how hard it is to write the testrunner with nimscript. Guess that has to wait for now :)

**Comment by zielmicha** [comment] 2016-01-09 23:27
1. `reactor.nim` is not tested on Mac OSX yet, but the only thing that may be broken is that some file from libuv is not compiled when it should be 
2. `reactor.nimble` is empty for now, as I don't use nimble for development (I've only added it to make compiler put modules in "reactor" namespace).

**Comment by zielmicha** [comment] 2016-01-09 23:28
Hmm, I think that you didn't checkout submodules (`git submodule update --init`). My intention is to bundle libuv with reactor, because it has unstable API (between different versions).

**Comment by oderwat** [comment] 2016-01-09 23:31
Yes! I totally overlooked that there are submodules!

Running tests now gives:

```
./runtests.py
tests/test_async_macro.nim ok
tests/test_async_macro_2.nim ok
Failure.
Expected:
b'resolved: @[8.8.8.8]\nresolved: @[0000:0000:0000:0000:0000:0000:0000:0001, 127.0.0.1]\nresolved: @[8.8.8.8, 2001:4860:4860:0000:0000:0000:0000:8888]'
Got:
b'resolved: @[8.8.8.8]\nresolved: @[0000:0000:0000:0000:0000:0000:0000:0001, 127.0.0.1, FE80:0000:0000:0000:0000:0000:0000:0001]\nresolved: @[8.8.8.8, 2001:4860:4860:0000:0000:0000:0000:8888]'
```

P.S.: The Nimble problem is maybe... a Nimble problem :) I don't think that it should hang "no matter whats in the file".

**Comment by zielmicha** [comment] 2016-01-09 23:36
The `resolv` test in current state is a bad idea as it may return different things depending on your system, I've disabled it for now.

**Comment by oderwat** [comment] 2016-01-09 23:38
Thank you! Tests are all ok now :+1:  lets see what I do with it :) I I can help with testing something mac specific give me a "ping" somewhere!

**Comment by dom96** [comment] 2016-01-09 23:44
@oderwat Are you sure you're running the latest Nimble? I get `FAILURE: Nothing to build. Did you specify a module to build using the `bin` key in your .nimble file?` when trying to run `nimble build`.

**Comment by oderwat** [comment] 2016-01-10 00:23
I get the same now @dom96 but @zielmicha did update the nimble file an hour ago. afaik it was just an empty file before. And when I do:

```
$ echo "" > reactor.nimble
$ nimble build
^CSIGINT: Interrupted by Ctrl-C.
```

it still hangs (for that empty file).

P.S.: Nimble is current. I even changed from ll-new to devel compiling it again to avoid regressions from the new ll compiler.

**Comment by dom96** [comment] 2016-01-10 00:33
@oderwat Just reproduced it. Strange bug. Will look into it.

**Edit:** Well, that was an embarrassing bug heh. Fixed now :)

**Closed as completed** 2016-01-10 01:00 UTC
