### ISSUE TITLE
Compile Error async/futuer.nim

### ISSUE THREAD

**Issue by 2vg** [zielmicha/reactor.nim#16] opened 2017-11-06 08:58 UTC
Hi !

i tried to use reactor module, but cant compie.

Source code is this,
```nim
import reactor

proc handleConn(conn: BytePipe): Future[void] {.async.} =
  # Pipe data from ``input`` to ``output``.
  pipe(conn.input, conn.output)

proc main() {.async.} =
  let conns = createTcpServer()
  # conns.incomingConnections has type Input[BytePipe]
  asyncFor conn in conns.incomingConnections:
    # If you have a Future that you want to ignore, don't use ``discard``.
    # Use ``ignore`` instead - it will print warning if Future finished with error
    handleConn(conn).ignore

when isMainModule: main().runMain()
```

And, Error is this,
```shell
/home/hoge/.nimble/pkgs/reactor-0.4.3/reactor/async/future.nim(347, 4) template/generic instantiation from here
/home/hoge/.nimble/pkgs/reactor-0.4.3/reactor/async/future.nim(211, 33) Error: undeclared identifier: 't'
```

**Comment by zielmicha** [comment] 2017-11-06 19:01
This issue was fixed a while ago, I've just created a new release. Please reinstall reactor and let me know if it helped.

**Comment by 2vg** [comment] 2017-11-07 00:15
thanks reply. but, another error :(
async.nim -> write code is tutorial's hello world

![default](https://user-images.githubusercontent.com/17700125/32470593-2f3ea49a-c39c-11e7-858a-acff4f3521e1.PNG)

**Comment by zielmicha** [comment] 2017-11-09 20:30
Tutorial is now fixed.
(This was also caused by Nim incompatible change)

**Closed as completed by zielmicha** 2017-11-09 20:30 UTC
