### ISSUE TITLE
Include libuv as a library

### ISSUE THREAD

**Issue by karantin2020** [zielmicha/reactor.nim#2] opened 2016-01-31 07:50 UTC
Hello, Zielmicha.

Great work! One question now. What is a reason to build libuv inside reactor.nim?
What is about connecting libuv as static or dynamic library?
There are two use cases:
- we have libuv library on system and don't need to build it again
- we want to use only libuv part of reactor.nim but not all lib. And we have libuv already

Your wrapper of libuv is better than the same in standard nim lib.
Thanks

**Comment by zielmicha** [comment] 2016-01-31 10:56
I don't use system libuv, because I want to avoid problems caused by linking to older/newer version of libuv (also, I want to make possible to apply custom patches to libuv if necessary). 
I'll accept patches that add option to link with libuv dynamically.

**Comment by zielmicha** [comment] 2016-02-05 20:26
Closing for now.

**Closed as completed by zielmicha** 2016-02-05 20:26 UTC
